/**
 * param_overrides.js
 * Automatically generated by calibrate.py v3.0
 * Ingests empirical anchors from 13 SEC quarters, LBNL grid data, and USITC trade flows
 * into the TESM Engine runtime environment.
 *
 * Generated: 2026-07-09 17:09:47
 */

window.TESM_CALIBRATED_OVERRIDES = {
  "gridConnectionDelay": 10,
  "powerGrowthCap": 0.43,
  "transformerShortage": 0.29,
  "downsizingRatio": 0.6,
  "siliconSupply": 205.66,
  "wacc": 0.085,
  "capitalReflexivity": 0.26
};

window.TESM_QUARTERLY_TIMESERIES = [
  {
    "quarter": "2023q1",
    "capexSumB": 40.38,
    "rpoSumB": 83.33,
    "revSumB": 301.34
  },
  {
    "quarter": "2023q2",
    "capexSumB": 37.88,
    "rpoSumB": 82.3,
    "revSumB": 299.38
  },
  {
    "quarter": "2023q3",
    "capexSumB": 36.33,
    "rpoSumB": 98.21,
    "revSumB": 315.02
  },
  {
    "quarter": "2023q4",
    "capexSumB": 38.6,
    "rpoSumB": 90.21,
    "revSumB": 332.1
  },
  {
    "quarter": "2024q1",
    "capexSumB": 39.43,
    "rpoSumB": 94.24,
    "revSumB": 338.28
  },
  {
    "quarter": "2024q2",
    "capexSumB": 46.17,
    "rpoSumB": 91.03,
    "revSumB": 344.54
  },
  {
    "quarter": "2024q3",
    "capexSumB": 51.08,
    "rpoSumB": 108.1,
    "revSumB": 355.7
  },
  {
    "quarter": "2024q4",
    "capexSumB": 72.37,
    "rpoSumB": 160.99,
    "revSumB": 438.1
  },
  {
    "quarter": "2025q1",
    "capexSumB": 63.21,
    "rpoSumB": 100.95,
    "revSumB": 381.36
  },
  {
    "quarter": "2025q2",
    "capexSumB": 77.38,
    "rpoSumB": 100.17,
    "revSumB": 382.46
  },
  {
    "quarter": "2025q3",
    "capexSumB": 91.54,
    "rpoSumB": 122.55,
    "revSumB": 407.24
  },
  {
    "quarter": "2025q4",
    "capexSumB": 102.21,
    "rpoSumB": 113.12,
    "revSumB": 437.75
  },
  {
    "quarter": "2026q1",
    "capexSumB": 116.32,
    "rpoSumB": 115.4,
    "revSumB": 439.03
  }
];

window.TESM_CALIBRATION_META = {
  "secQuartersProcessed": 13,
  "secQuarterRange": "2023q1 - 2026q1",
  "capexCAGR": 42.3,
  "rpoCAGR": 11.5,
  "hyperscalers": "MICROSOFT, AMAZON, ALPHABET, SALESFORCE, META PLATFORMS, ORACLE",
  "lbnlGridProjects": 10775,
  "lbnlMeanQueueDays": 831,
  "generatedAt": "2026-07-09 17:09:47"
};

// Apply values to the default parameters template block
if (window.TESMEngine) {
  Object.assign(window.TESMEngine.DEFAULT_PARAMS, window.TESM_CALIBRATED_OVERRIDES);
  console.log("TESM Engine Calibrated with Real-World Data (" + window.TESM_CALIBRATION_META.secQuartersProcessed + " SEC quarters):", window.TESM_CALIBRATED_OVERRIDES);
}
